export const PRODUCT_ORDER_REQUEST = 'PRODUCT_ORDER_REQUEST';
export const PRODUCT_ORDER_SUCCESS = 'PRODUCT_ORDER_SUCCESS';
export const PRODUCT_ORDER_FAIL = 'PRODUCT_ORDER_FAIL';
export const PRODUCT_ORDER_RESET = 'PRODUCT_ORDER_RESET';