export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const MY_DETAILS_REQUEST = 'MY_DETAILS_REQUEST';
export const MY_DETAILS_SUCCESS = 'MY_DETAILS_SUCCESS';
export const MY_DETAILS_FAIL = 'MY_DETAILS_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_PROFILEUPDATE_REQUEST = 'USER_PROFILEUPDATE_REQUEST';
export const USER_PROFILEUPDATE_SUCCESS = 'USER_PROFILEUPDATE_SUCCESS';
export const USER_PROFILEUPDATE_FAIL = 'USER_PROFILEUPDATE_FAIL';
export const USER_PROFILEUPDATE_RESET = 'USER_PROFILEUPDATE_RESET';

export const USER_SIGNOUT = 'USER_SIGNOUT';